spring:
  datasource:
    username: jncsgj
    password: JNcsgj@com123!
    url: jdbc:mysql://172.54.134.232:3306/dumpsite?useSSL=true&serverTimezone=UTC
    #url: jdbc:mysql://localhost:3306/dumpsite?useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8870

tianfu:
  secret: "606e87ed-6d0e-4a79-bd61-d710a07de0e0"
  key: "40b66dec-a664-40ef-bc01-b13ad7094568"


#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

